---
- name: Setting up ownClound
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: targets
  tasks:
    - name: Update cache
      become: yes
      become_method: sudo
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install Packages
      become: yes
      become_method: sudo
      apt:
        name: ["nginx", "mariadb-server", "mariadb-client"]
        state: present
